version: '3.1'

services:
  postgres:
    image: postgres:13.6
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test_proj_db
